In [19]:
A = [[1, 1, 1], [0, 1, 2], [0, 0, 3]]

In [20]:
b = [[3], [3], [3]]

In [3]:
B_inv = np.linalg.inv([[1, 1, 1], [0, 1, 2], [0, 0, 3]])

In [6]:
B_inv

array([[ 1.        , -1.        ,  0.33333333],
       [ 0.        ,  1.        , -0.66666667],
       [ 0.        ,  0.        ,  0.33333333]])

In [ ]:
[[]]

In [23]:
np.dot([[1, 0, 1], [0, 1, -3], [0, 0, 1]], [[4],[14],[3]])

array([[7],
       [5],
       [3]])

In [5]:
np.dot(B_inv, [[3], [3], [3]])

array([[1.],
       [1.],
       [1.]])