In [27]:
np.empty([num_samples+1, 2]).shape

(501, 2)

In [21]:
def gibbs_sampler(initial_point, num_samples, mean, cov):

    point = np.array(initial_point)
    samples = np.empty([num_samples + 1, 2]) # Creates an empty numpy array with shape (num_samples+1, 2)

    samples[0] = point
    tmp_points = np.empty([num_samples, 2]) #inbetween points

    for i in range(num_samples):
        # Sample from p(x_0|x_1)
        point = conditional_sampler(0, point, mean, cov)
        tmp_points[i] = point
        # Sample from p(x_1|x_0)
        point = conditional_sampler(1, point, mean, cov)
        samples[i+1] = point

    return samples, tmp_points

def conditional_sampler(sampling_index, current_x, mean, cov):
    conditioned_index = 1 - sampling_index 
    # The above line works because we only have 2 variables, x_0 & x_1
    a = cov[sampling_index, sampling_index]
    b = cov[sampling_index, conditioned_index]
    c = cov[conditioned_index, conditioned_index]
  
    mu = mean[sampling_index] + (b * (current_x[conditioned_index] - mean[conditioned_index]))/c
    
    sigma = np.sqrt(a-(b**2)/c)
    new_x = np.copy(current_x)
    new_x[sampling_index] = np.random.randn()*sigma + mu
    
    return new_x

In [22]:
initial_point = [-9.0, -9.0]
num_samples = 500

mean = np.array([0, 0])
cov = np.array([[10, 3], 
                [3, 5]])

gibbs_sampler(initial_point, num_samples, mean, cov)

[[0.00000000e+000 2.40955815e-320]
 [0.00000000e+000 6.94658108e-310]
 [4.94065646e-324 6.94658108e-310]
 ...
 [1.72291756e-047 5.20460916e-090]
 [6.12743486e-154 8.09244594e-153]
 [2.74322230e-057 1.05118731e-153]] S


(array([[-9.        , -9.        ],
        [-5.35874836,  0.41698587],
        [-0.47243362,  2.4352714 ],
        ...,
        [ 1.36822659,  0.21976892],
        [-5.65643745, -2.55728575],
        [ 1.47566959, -1.1055591 ]]),
 array([[-5.35874836e+00, -9.00000000e+00],
        [-4.72433620e-01,  4.16985868e-01],
        [ 1.09716443e+00,  2.43527140e+00],
        [ 1.68371842e+00, -1.74991138e-01],
        [-2.51553431e-01,  3.23594179e+00],
        [-3.25876280e-01, -2.99514065e+00],
        [ 1.97394017e+00,  2.05358843e+00],
        [-3.35264441e+00, -2.56118018e+00],
        [-3.48224009e+00, -4.22192152e+00],
        [ 3.71519311e-02, -7.39220482e-01],
        [-1.76234941e-01, -1.30921356e+00],
        [ 7.25803492e+00,  1.35352204e+00],
        [-7.03126900e+00,  4.40536789e+00],
        [ 3.60177929e+00,  4.73369701e-01],
        [-1.93235608e+00,  3.47086941e+00],
        [-8.18883223e-01,  6.82886826e-01],
        [ 3.30676838e+00,  6.83813203e-01],
        [-5.29894211e